### ISSUE TITLE
Open link in new tab

### ISSUE THREAD

**Issue by dolarsrg** [mtrpcic/pathjs#16]
Hi,

I'm trying to fix an issue, but I'm a little bit lost and maybe you thought about this already.

When you want to open a Path.js link in a new tab you can do it rightclicking in the link and selecting "Open In New Tab" in the Browser, but it's not working clicking on the link with the mousewheel at windows or doing Click + command on Mac OS X.

Do you know why is it happening?

Best regards!

**Comment by mtrpcic** [comment]
I'm trying to recreate the scenario you described but so far haven't been able to.  I'm testing it with the example page [here](mtrpcic.github.com/pathjs/hashtag_basic.html).  I've tried "right click -> open in new tab", mousewheel middle-click, and command+click.  All testing was done on OSX 10.6 in FireFox and Chrome.  Could you give me a bit more details? (PathJS version, browser, etc?).

**Comment by dolarsrg** [comment]
Hi,

Thanks so much for the answer!

I see. I'm using the same brosers and OS than you. I think the difference in my scenario is that I'm using HTML5 integration (not the # one).

Here I have the problem I'm describing: http://mtrpcic.github.com/pathjs/html5_basic.html

But it's working perfectly in the hashtag one.

**Comment by mtrpcic** [comment]
HTML5 Pushstate does not support being opened in a new tab.  This is because the path is a fully qualified one, which gets sent entirely to the HTTP server before PathJS can be loaded.  This was outlined in the [Wiki](https://github.com/mtrpcic/pathjs/wiki/HTML5-PushState).

To properly support "open in a new tab", you must have that actual full route, server side, return the layout/entire DOM that you want on an HTTP request, and also render only the content subset you would like upon an AJAX call.  This is a server side issue, and not dependant on PathJS.
