### ISSUE TITLE
Example page view source doesn't work in Chrome

### ISSUE THREAD

**Issue by DouglasLivingstone** [mtrpcic/pathjs#20]
On http://mtrpcic.github.com/pathjs/html5_basic.html there is an instruction to view the source of the page to see what's going on. That won't work in Chrome after clicking on any of push state links, eg Users.

View source in Chrome opens a new tab to a view source url, for example:

```
view-source:http://mtrpcic.github.com/users
```

This does a request for `http://mtrpcic.github.com/users`, then shows the source of the GitHub 404 page.

**Comment by dannyc** [comment]
This is not an issue with Chrome's view source this is an issue with the page's updated URL losing all of it's path after the domain.  You would run into a 404 error if you tried to do a page refresh (ctrl +r) since the URL does not map to real resource.  The initial URL is 
    http://mtrpcic.github.com/pathjs/html5_basic.html
after clicking on about:
    http://mtrpcic.github.com/about
the "/pathjs/html5_basic.html" got lost.  Without digging too much into the code the problem is either in the example's call to Path.history.pushState or in pathjs's pushState implementation ignoring the path.  I imagine that this is not expected behavior and the path should be maintained, otherwise deep linking, bookmarking, (view source, open new tabs), etc. is impossible.

**Comment by DouglasLivingstone** [comment]
Agreed, this isn't a bug in Chrome. It works in some browsers (for example, Safari always shows the source for the initial page) so I included full steps to reproduce.

A simple fix would be to use paths like `/pathjs/html5_basic.html?page=about` so that extra files are not required in the repository.

**Comment by mtrpcic** [comment]
This isn't an issue with PathJS, it's an issue with some browsers implementation of the "View Source" function.  Some browsers take the current pages source, while others do another request.  If you'd like to view the source of the HTML5 examples, simply view the source **before** modifying the URL via interaction with HTML5 pushState.
